src/Entity/BookingCategory.php
<?php

namespace Tigris\CalendarBundle\Entity;

use App\Entity\Calendar\Resource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Tree\Traits\NestedSetEntity;
use JMS\Serializer\Annotation as JMS;
use Symfony\Component\Validator\Constraints as Assert;
use Tigris\BaseBundle\Utils\Utils;
use Tigris\CalendarBundle\Repository\BookingCategoryRepository;

#[ORM\Entity(repositoryClass: BookingCategoryRepository::class)]
#[ORM\Table(name: 'calendar_booking_category')]
#[Gedmo\Tree(type: 'nested')]
class BookingCategory implements \Stringable
{
    use NestedSetEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int|null $id = null;

    #[ORM\Column(length: 120)]
    #[Assert\NotBlank()]
    private string $name;

    #[ORM\Column(length: 7, nullable: true)]
    private string|null $color = null;

    #[ORM\OneToMany(targetEntity: Resource::class, mappedBy: 'category')]
    #[JMS\Exclude]
    private $resources;

    #[ORM\ManyToOne(inversedBy: 'children')]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    #[JMS\Exclude]
    #[Gedmo\TreeParent]
    #[Gedmo\SortableGroup]
    private BookingCategory|null $parent = null;

    #[ORM\OneToMany(targetEntity: BookingCategory::class, mappedBy: 'parent')]
    #[ORM\OrderBy(['left' => 'ASC'])]
    #[JMS\Exclude]
    private Collection $children;

    #[ORM\Column]
    #[Gedmo\SortablePosition]
    private int $position;

    public function __construct()
    {
        $this->left = 0;
        $this->level = 0;
        $this->right = 0;
        $this->root = null;
        $this->children = new ArrayCollection();
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Get the value of name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Set the value of name.
     */
    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of color.
     *
     * @return string
     */
    public function getColor(): ?string
    {
        return $this->color;
    }

    /**
     * Set the value of color.
     */
    public function setColor(string $color): static
    {
        $this->color = $color;

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    /**
     * Get the value of resources.
     */
    public function getResources()
    {
        return $this->resources;
    }

    /**
     * Set the value of resources.
     */
    public function setResources($resources): static
    {
        $this->resources = $resources;

        return $this;
    }

    public function getColorLightness()
    {
        $rgb = Utils::HTMLToRGB($this->color);
        $hsl = Utils::RGBToHSL($rgb);

        return $hsl->lightness;
    }

    /**
     * @return mixed
     */
    public function getRoot()
    {
        return $this->root;
    }

    public function setRoot(mixed $root): static
    {
        $this->root = $root;

        return $this;
    }

    public function getParent(): ?\Tigris\CalendarBundle\Entity\BookingCategory
    {
        return $this->parent;
    }

    public function setParent(mixed $parent): static
    {
        $this->parent = $parent;
        if (is_null($parent)) {
            $this->level = 0;
        }

        return $this;
    }

    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function setChildren(mixed $children): static
    {
        $this->children = $children;

        return $this;
    }

    /**
     * Get the value of position.
     */
    public function getPosition(): int
    {
        return $this->position;
    }

    public function setPosition(int $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getResourceIds(): array
    {
        $ids = [];
        foreach ($this->resources as $resource) {
            $ids[] = $resource->getId();
        }

        return $ids;
    }
}

src/Entity/Item.php
<?php

namespace Tigris\CalendarBundle\Entity;

use App\Entity\Calendar\Event;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use Tigris\CalendarBundle\Entity\Model\EventModel;

#[ORM\Entity]
#[ORM\Table(name: 'calendar_item')]
#[ORM\InheritanceType('SINGLE_TABLE')]
#[ORM\DiscriminatorColumn(name: 'type', type: 'string')]
#[ORM\DiscriminatorMap(['event' => Event::class, 'booking' => 'Booking'])]
#[JMS\Discriminator(field: 'mapType', disabled: false, map: ['booking' => Booking::class, 'event' => Event::class, 'eventModel' => EventModel::class])]
abstract class Item
{
    public $type;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    protected ?int $id = null;

    #[ORM\Column(length: 180)]
    protected string $name;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    protected ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    protected \DateTime $startDate;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    protected \DateTime $endDate;

    /**
     * @TODO Delete this field
     */
    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    protected ?\DateTime $startTime;

    /**
     * @TODO Delete this field
     */
    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    protected $endTime;

    #[ORM\Column]
    protected bool $allDay = false;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $cancelDate = null;

    public function __construct()
    {
        $this->startDate = new \DateTime();
        $this->endDate = new \DateTime();
        $this->startTime = new \DateTime();
        $this->endTime = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = strip_tags((string) $description, ['br']);

        return $this;
    }

    #[JMS\VirtualProperty]
    public function getDuration(): int
    {
        $interval = $this->startDate->diff($this->endDate);
        $total = 0;

        $total += (int) $interval->format('%a') * 24 * 60;
        $total += (int) $interval->format('%h') * 60;

        return $total + (int) $interval->format('%i');
    }

    #[JMS\VirtualProperty]
    public function getFormattedDuration(string $format = '%hH%I'): string
    {
        $interval = $this->startDate->diff($this->endDate);

        return $interval->format($format);
    }

    public function setDuration($minutes): self
    {
        $this->endDate = clone $this->startDate;
        $this->endDate->add(new \DateInterval(sprintf('PT%sM', $minutes)));

        return $this;
    }

    public function setStart(\DateTime $start): self
    {
        $this->startDate = $start;

        return $this;
    }

    public function getStartDate(): \DateTime
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTime $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): \DateTime
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTime $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function setEnd(\DateTime $end): self
    {
        $this->endDate = $end;

        return $this;
    }

    public function getStartTime(): ?\DateTime
    {
        return $this->startTime;
    }

    public function setStartTime(?\DateTime $startTime): self
    {
        $this->startDate = clone $this->startDate;
        $this->startDate->setTime($startTime->format('G'), $startTime->format('i'));
        
        $this->startTime = $startTime;

        return $this;
    }

    public function getEndTime(): ?\DateTime
    {
        return $this->endTime;
    }

    public function setEndTime(?\DateTime $endTime): self
    {
        $this->endDate = clone $this->endDate;
        $this->endDate->setTime($endTime->format('G'), $endTime->format('i'));
        
        $this->endTime = $endTime;

        return $this;
    }

    public function getStartDateTime(): \DateTime
    {
        return $this->startDate;
    }

    public function getEndDateTime(): \DateTime
    {
        return $this->endDate;
    }

    public function getAllDay(): bool
    {
        return $this->allDay;
    }

    public function setAllDay(bool $allDay): self
    {
        $this->allDay = $allDay;

        return $this;
    }

    public function getCancelDate(): ?\DateTime
    {
        return $this->cancelDate;
    }

    public function setCancelDate(?\DateTime $cancelDate): self
    {
        $this->cancelDate = $cancelDate;

        return $this;
    }

    public function isCanceled(): bool
    {
        return $this->cancelDate instanceof \DateTime;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Controller/Admin/BookingController.php
<?php

namespace Tigris\CalendarBundle\Controller\Admin;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Tigris\BaseBundle\Controller\Admin\BaseController;
use Tigris\BaseBundle\Repository\UserRepository;
use Tigris\BaseBundle\Traits\FormTrait;
use Tigris\CalendarBundle\Controller\BookingControllerTrait;
use Tigris\CalendarBundle\Repository\BookingCategoryRepository;

#[IsGranted('ROLE_ADMIN')]
#[Route(path: '/calendar/admin/booking')]
class BookingController extends BaseController
{
    use FormTrait;
    use BookingControllerTrait;
    private $routePrefix = 'admin_';
    
    private $viewPrefix = 'admin/';

    public function generateBreadcrumbs(array $routes = []): void
    {
        $routes = array_merge([
            'calendar.menu.booking' => null,
            // 'calendar.menu.calendar' => ['route' => 'tigris_calendar_admin_booking_index'],
        ], $routes);

        parent::generateBreadcrumbs($routes);
    }

    #[Route(path: '/list')]
    public function list(BookingCategoryRepository $bookingCategoryRepository, UserRepository $userRepository): Response
    {
        $this->generateBreadcrumbs([
            'calendar.menu.booking_list' => ['route' => 'tigris_calendar_admin_booking_list'],
        ]);
        $categories = $bookingCategoryRepository->findAll();
        $users = $userRepository->findBy(['enabled' => true], ['username' => 'asc']);
        $startDate = new \DateTime();
        $startDate->sub(new \DateInterval('P3M'));
        
        $endDate = new \DateTime();
        $endDate->add(new \DateInterval('P3M'));

        return $this->render('@TigrisCalendar/admin/booking/list.html.twig', [
            'categories' => $categories,
            'users' => $users,
            'startDate' => $startDate,
            'endDate' => $endDate,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace Tigris\CalendarBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Tigris\BaseBundle\Controller\BaseController;
use Tigris\BaseBundle\Entity\Model\User;
use Tigris\BaseBundle\Traits\FormTrait;
use Tigris\CalendarBundle\Entity\Model\ResourceModel;
use Tigris\CalendarBundle\Repository\BookingCategoryRepository;
use Tigris\CalendarBundle\Repository\BookingRepository;
use Tigris\CalendarBundle\Repository\ResourceRepository;

#[Route(path: 'booking')]
class BookingController extends BaseController
{
    use FormTrait;
    use BookingControllerTrait;
    private $routePrefix = '';
    
    private $viewPrefix = '';

    public function _previewWidget(Request $request, BookingRepository $bookingRepository, ResourceRepository $resourceRepository, array $excludeDays = []): Response
    {
        $year = $request->query->get('y', date('Y'));
        $month = $request->query->get('m', date('m'));
        $dayCount = cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y'));

        $bookings = $bookingRepository->findByMonth($month, $year);
        $resources = $resourceRepository->findBy(['visibility' => ResourceModel::VISIBILITY_ALL, 'status' => ResourceModel::STATUS_AVAILABLE]);

        // Generate array
        $days = [];
        for ($i = 1; $i <= $dayCount; ++$i) {
            $days[$i] = ['count' => 0];

            foreach ($resources as $resource) {
                $days[$i][$resource->getId()] = ['count' => 0, 'bookings' => [], 'name' => $resource->geTName()];
            }
        }

        foreach ($bookings as $booking) {
            $start = $booking->getStartDate();
            $end = $booking->getEndDate();
            $resource = $booking->getResource();

            $dayStart = $start->format('d');
            $dayEnd = $end->format('d');

            if ($start->format('m') != $end->format('m')) { // Pour les reservations à cheval sur deux mois
                if ($month == $start->format('m')) { // On consulte le premier mois
                    $dayEnd = $dayCount;
                } elseif ($month == $end->format('m')) { // On consulte le dernier mois
                    $dayStart = 1;
                } else {
                    $dayStart = 1;
                    $dayEnd = $dayCount;
                }
            }

            for ($i = (int) $dayStart; $i <= (int) $dayEnd; ++$i) {
                if (isset($days[$i][$resource->getId()])) {
                    ++$days[$i][$resource->getId()]['count'];
                    ++$days[$i]['count'];
                    $days[$i][$resource->getId()]['bookings'][] = $booking;
                }
            }
        }

        $prevMonth = (1 == $month) ? 12 : $month - 1;
        $nextMonth = (12 == $month) ? 1 : $month + 1;
        $prevYear = (1 == $month) ? $year - 1 : $year;
        $nextYear = (12 == $month) ? $year + 1 : $year;

        return $this->render('@TigrisCalendar/booking/_preview_widget.html.twig', [
            'nbDays' => $dayCount,
            'days' => $days,
            'resources' => $resources,
            'month' => $month,
            'year' => $year,
            'nextMonth' => $nextMonth,
            'prevMonth' => $prevMonth,
            'nextYear' => $nextYear,
            'prevYear' => $prevYear,
            'excludeDays' => $excludeDays,
        ]);
    }

    #[Route(path: '/list')]
    public function list(BookingCategoryRepository $bookingCategoryRepository): Response
    {
        $this->generateBreadcrumbs([
            'calendar.menu.booking_userlist' => ['route' => 'tigris_calendar_booking_list'],
        ]);
        $categories = $bookingCategoryRepository->findAll();
        $startDate = new \DateTime();
        $startDate->sub(new \DateInterval('P3M'));
        
        $endDate = new \DateTime();
        $endDate->add(new \DateInterval('P3M'));

        return $this->render('@TigrisCalendar/booking/list.html.twig', [
            'categories' => $categories,
            'startDate' => $startDate,
            'endDate' => $endDate,
        ]);
    }

    #[Route(path: '/user-data', options: ['expose' => true])]
    public function userData(Request $request, BookingRepository $bookingRepository): Response
    {
        $user = $this->getUser();

        if (!$user instanceof User) {
            throw new AccessDeniedException();
        }

        $request->query->set('user', $user->getId());

        return $this->data($request, $bookingRepository);
    }
}

templates/booking/_booking_calendar.html.twig
{% macro booking_category(category) %}
    {% for resource in category.resources %}
        {% include '@TigrisCalendar/booking/_booking_resource.html.twig' with {'entity': resource } %}
    {% endfor %}

    {% if category.children is not empty %}
        {% for child in category.children %}
            <h3>{{ child }}</h3>
            {{ _self.booking_category(child) }}
        {% endfor %}
    {% endif %}
{% endmacro %}
{#
<div id="booking-calendar">
    <div class="row">
        {% if allowAdd or is_granted('ROLE_ADMIN') %}
        <div class="col-md-3">
            <div id="booking-categories">
                {% for category in categories %}
                {% set mainLoop = loop %}
                <div class="card card-sm mb-3">
                    <div class="card-header">
                        {{ category }}
                    </div>

                    <div class="card-body">
                        {% if category.resources is not empty %}
                            {% for resource in category.resources %}
                                {% include '@TigrisCalendar/booking/_booking_resource.html.twig' with {'entity': resource } %}
                            {% endfor %}
                        {% endif %}
                        <div class="accordion">
                            {% for child in category.children %}
                            <div class="card card-smart-border mb-2" style="border-top-color:{{ child.color }}">
                                <div class="card-header resource-category-header" id="heading-cat-{{ child.id }}">
                                    <h2 class="mb-0">
                                        <a href="#" data-bs-toggle="collapse" data-bs-target="#collapse-cat-{{ child.id }}" aria-expanded="true" aria-controls="collapse-cat-{{ child.id }}">
                                            <span class="icon">{{ ".icon-chevron-down"|parse_icons }}</span>{{ child }}
                                        </a>
                                    </h2>
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" {% if child.id == defaultSelectedCategory %} checked{% endif %} data-select-category="{{ child.id }}" id="category-select-{{ child.id }}">
                                        <label class="form-check-label" for="category-select-{{ child.id }}"> </label>
                                    </div>
                                </div>   

                                <div id="collapse-cat-{{ child.id }}" class="collapse {% if child.id == defaultSelectedCategory %}show{% endif %}" aria-labelledby="heading-cat-{{ child.id }}" data-parent="#booking-categories">
                                    <div class="card-body resource-droppable">
                                        {{ _self.booking_category(child) }}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        
        {% endif %}
        <div class="col">
            <div class="card">
                <div id="calendar" class="tigris-calendar" init-view="timeGridWeek" list-route="tigris_calendar{% if admin %}_admin{% endif %}_booking_calendaritems" show-item-route="tigris_calendar{% if admin %}_admin{% endif %}_booking_show" new-item-route="tigris_calendar{% if admin %}_admin{% endif %}_booking_new">
                </div>
            </div>
        </div>
    </div>
</div>#}
<div id="booking-calendar">
    <tigris-booking-calendar v-slot="{selectedResources, triggerResourceSelect, selectResources, unselectResources}" :active-days="[{{ activeDays|join(',') }}]" :prefered-resources="[{{ defaultSelectedResource ?? '' }}]">
        <div id="booking-categories">
            {% for category in categories %}
            {% set mainLoop = loop %}
            <div class="card card-sm mb-3">
                <div class="card-header">
                    {{ category }}
                </div>

                <div class="card-body">
                    {% if category.resources is not empty %}
                        {% for resource in category.resources %}
                            {% include '@TigrisCalendar/booking/_booking_resource.html.twig' with {'entity': resource } %}
                        {% endfor %}
                    {% endif %}
                    <div class="accordion">
                        {% for child in category.children %}
                        <div class="card card-smart-border mb-2" style="border-top-color:{{ child.color }}">
                            <div class="card-header resource-category-header" id="heading-cat-{{ child.id }}">
                                <h2 class="mb-0">
                                    <a href="#" data-bs-toggle="collapse" data-bs-target="#collapse-cat-{{ child.id }}" aria-expanded="true" aria-controls="collapse-cat-{{ child.id }}">
                                        <span class="icon">{{ ".icon-chevron-down"|parse_icons }}</span>{{ child }}
                                    </a>
                                </h2>
                                {#<div class="form-check">
                                    <input type="checkbox" class="form-check-input" {% if child.id == defaultSelectedCategory %} checked{% endif %} data-select-category="{{ child.id }}" id="category-select-{{ child.id }}">
                                    <label class="form-check-label" for="category-select-{{ child.id }}"> </label>
                                </div>#}
                                <div>
                                    <button type="button" class="btn btn-outline-secondary btn-sm" @click="selectResources([{{ child.resourceIds|join(',') }}])" data-bs-toggle="tooltip" title="{{ 'calendar.category.select_all'|trans }}">{{ '.icon-eye'|parse_icons }}</button>
                                    <button type="button" class="btn btn-outline-secondary btn-sm ms-1" @click="unselectResources([{{ child.resourceIds|join(',') }}])" data-bs-toggle="tooltip" title="{{ 'calendar.category.unselect_all'|trans }}">{{ '.icon-eye-slash'|parse_icons }}</button>
                                </div>
                                
                            </div>   

                            <div id="collapse-cat-{{ child.id }}" class="collapse {% if child.id == defaultSelectedCategory %}show{% endif %}" aria-labelledby="heading-cat-{{ child.id }}" data-parent="#booking-categories">
                                <div class="card-body resource-droppable">
                                    {{ _self.booking_category(child) }}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </tigris-booking-calendar>
</div>

templates/booking/_booking_resource.html.twig
<div class="booking-resource media">
    {% if entity.image is not null %}
    <img class="me-2 booking-resource-image" src="{{ asset(entity.image.webPath('thumbnail')) }}" alt="{{ entity.name }}">
    {% endif %}
    <div class="media-body">
        <div class="resource-infos">
            <h4>{{ entity.name }}</h4>
            <div class="form-check">
                <input type="checkbox" class="form-check-input select-resource" id="resource-select-{{ entity.id }}" data-category="{{ entity.category.id }}" v-model="selectedResources" value="{{ entity.id }}" @change="(e) => triggerResourceSelect({{ entity.id}}, e.target.checked)">
                <label class="form-check-label" for="resource-select-{{ entity.id }}">{{ 'calendar.booking.show_resource'|trans }}</label>
            </div>
        </div>
        {% if entity.status == constant('STATUS_AVAILABLE', entity) %}
        <div class="btn-drag btn {% if entity.category.colorLightness < 200 %}text-light{% endif %} btn-sm" style="background-color:{{ entity.category.color }}" data-id="{{ entity.id }}" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="{{ 'calendar.booking.book_tooltip'|trans }}" title="{{ 'calendar.booking.book_tooltip'|trans }}">
            {{ 'calendar.booking.book'|trans }}
        </div>
        {% else %}
        <div class="resource-unavailable">
            
            {% if entity.statusMessage is not empty %}
            <div class="text-danger">{{ entity.statusMessage }}</div>
            {% else %}
            <div class="badge bg-danger">{{ 'calendar.resource.status.unavailable'|trans }}</div>
            {% endif %}

        </div>
        {% endif %}
    </div>
</div>

templates/booking/_form.html.twig
{% if form.user is defined %}
    {{ form_row(form.user) }}
{% endif %}
{{ form_row(form.description) }}
<div>

    {{ form_label(form.startDate) }}
    <div class="d-flex my-2">
        <div class="me-2">{{ form_widget(form.startDate) }}</div>
        {# <div>{{ form_widget(form.startTime) }}</div> #}
    </div>
</div>

<div>
    {% if form.duration is defined %}
        {{ form_label(form.duration) }}
        <div class="my-2">
            {# <div class="me-2">{{ form_widget(form.endDate) }}</div> #}
            <div>{{ form_widget(form.duration) }}</div>
        </div>
    {% elseif form.endDate is defined %}
    <div class="d-flex my-2">
        <div class="me-2">{{ form_row(form.endDate) }}</div>
    </div>
    
    {% endif %}

</div>

templates/booking/_info.html.twig
<div class="booking">
    <div class="row">
        <div class="col-lg-6">
            <h2>{{ 'calendar.booking.booking'|trans }}</h2>
            <div class="info-box bg-info text-light">
                <div class="info-box-icon">
                    {{ '.icon-calendar-alt'|parse_icons }}
                </div>
                <div class="info-box-content">
                    <div class="dates">
                    {% if entity.startDate == entity.endDate %}
                        {{ entity.startDateTime|format_datetime("medium", "short")}} - {{ entity.endTime|format_datetime("none", "short")}}
                    {% else %}
                        {{ entity.startDateTime|format_datetime("medium", "short")}} - {{ entity.endDateTime|format_datetime("medium", "short")}}
                    {% endif %}
                    </div>
                    <div class="duration">{{ entity.formattedDuration }}</div>
                </div>
                
            </div>
        </div>

        <div class="col-lg-6">
            <h2>{{ 'calendar.booking.user'|trans }}</h2>
            <div class="info-box bg-body-tertiary">
                <div class="info-box-icon">
                    {{ '.icon-user'|parse_icons }}
                </div>
                <div class="info-box-content">
                    {{ entity.user }}
                </div>
            </div>
        </div>
    </div>

    {% if  entity.description is not empty %}
    <div class="description">
        {{ entity.description|raw }}
    </div>
    {% endif %}
</div>
    

templates/booking/cancel.html.twig
{% extends app.request.xmlHttpRequest ? '@TigrisBase/ajax-layout.html.twig': '@TigrisBase/layout.html.twig' %}
{% block main %}
    
    {% embed '@TigrisBase/decorators/_form.html.twig' with {'type': 'danger'} %}
    {% block title %}{{ 'calendar.booking.cancel.title'|trans }}{% endblock %}
    {% block body %}
    <p>{{ 'calendar.booking.cancel.message'|trans({"%entity%": entity.resource})|raw }}</p>
    {% endblock %}
    {% endembed %}
{% endblock %}

templates/booking/cannot_booking.html.twig
{% extends app.request.xmlHttpRequest ? '@TigrisBase/ajax-layout.html.twig' : '@TigrisBase/layout.html.twig' %}
{% block main %}
    {% embed '@TigrisBase/decorators/_card.html.twig' %}
    {% block body %}
    <div class="alert alert-danger">
        {{ 'calendar.booking.cannot_booking'|trans }}
        <div>
            <strong>{{ ('calendar.booking.reason.'~reason)|trans }}</strong>
        </div>
    </div>
    {% endblock %}
    {% endembed %}
{% endblock %}

templates/booking/edit.html.twig
{% extends app.request.xmlHttpRequest 
        ? '@TigrisBase/ajax-layout.html.twig'
        : '@TigrisBase/layout.html.twig' %}
{% block main %}
    
    {% embed '@TigrisBase/decorators/_form.html.twig' with {'class': ''} %}
    {% block title %}{{ 'calendar.booking.edit.title'|trans }}{% endblock %}
    {% block body %}
    {% include '@TigrisCalendar/booking/_form.html.twig' %}
    {% endblock %}
    {% endembed %}
{% endblock %}

templates/booking/index.html.twig
{% extends '@TigrisBase/layout.html.twig' %}
{% block title %}{{ 'calendar.booking.title'|trans|parse_icons }}{% endblock %}
{% block main %}
{% include "@TigrisCalendar/booking/_booking_calendar.html.twig" with {"admin": false} %}

{% endblock %}

templates/booking/new.html.twig
{% extends app.request.xmlHttpRequest 
        ? '@TigrisBase/ajax-layout.html.twig'
        : '@TigrisBase/layout.html.twig' %}
{% block main %}
    
    {% embed '@TigrisBase/decorators/_form.html.twig' with {'class': ''} %}
    {% block title %}{{ 'calendar.booking.add.title'|trans({"name": entity.resource.name}) }}{% endblock %}
    {% block body %}
    {% include '@TigrisCalendar/booking/_form.html.twig' %}
    {% endblock %}
    {% endembed %}
{% endblock %}